import type { Polygon } from 'geojson'
import type { ExtractionResult, PlanZone, Constraint } from '../types'
import { buildProposedFeatures } from '../viewer/buildingGeometry'
import { roofTypeFromLabel } from './roof'

/** Trigger a browser download of a string as a file. */
function download(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function getConstraintValue(constraints: Constraint[], key: string): string | number | undefined {
  return constraints.find((c) => c.key === key)?.value
}

function toNum(v: string | number | undefined, fallback: number): number {
  if (v == null) return fallback
  const n = typeof v === 'number' ? v : Number(String(v).replace(',', '.'))
  return Number.isFinite(n) ? n : fallback
}

/**
 * Export the proposed building(s) as a 3D GeoJSON FeatureCollection.
 * Each zone produces wall + roof features with full metadata.
 * Directly importable into QGIS as a vector layer with 3D renderer.
 */
export function exportGeoJSON(
  result: ExtractionResult,
  proposed: Record<string, string | number>,
  activeFootprint: Polygon,
) {
  const zones = result.zones ?? [{ id: 'zone-1', name: 'Plangebiet', constraints: result.constraints, footprint: result.footprint }]

  const allFeatures: GeoJSON.Feature[] = []

  for (const zone of zones) {
    const heightM = toNum(getConstraintValue(zone.constraints, 'max_height') ?? proposed['max_height'], 9)
    const roofLabel = String(getConstraintValue(zone.constraints, 'roof_type') ?? proposed['roof_type'] ?? 'unknown')
    const roofType = roofTypeFromLabel(roofLabel)
    const pitchDeg = toNum(getConstraintValue(zone.constraints, 'roof_pitch') ?? proposed['roof_pitch'], 35)
    const footprint = zone.footprint ?? activeFootprint

    const fc = buildProposedFeatures(footprint, heightM, roofType, pitchDeg, true)

    for (const f of fc.features) {
      allFeatures.push({
        ...f,
        properties: {
          ...f.properties,
          zone_id: zone.id,
          zone_name: zone.name,
          plan_name: result.plan.name,
          plan_number: result.plan.planNumber ?? '',
          municipality: result.plan.municipality,
          crs: result.plan.crs,
          roof_type: roofLabel,
          roof_pitch: pitchDeg,
          max_height: heightM,
          grz: toNum(getConstraintValue(zone.constraints, 'grz'), 0),
          gfz: toNum(getConstraintValue(zone.constraints, 'gfz'), 0),
          floors: toNum(getConstraintValue(zone.constraints, 'floors'), 0),
        },
      })
    }
  }

  const geojson: GeoJSON.FeatureCollection = {
    type: 'FeatureCollection',
    features: allFeatures,
  }

  const filename = `${result.plan.name || 'planraum'}_3d.geojson`.replace(/\s+/g, '_')
  download(JSON.stringify(geojson, null, 2), filename, 'application/geo+json')
}

/**
 * Export as CityGML LOD2 — the format the hackathon challenge asks for.
 * Generates a minimal CityGML 2.0 document with Building elements containing
 * WallSurface and RoofSurface for each zone.
 */
export function exportCityGML(
  result: ExtractionResult,
  proposed: Record<string, string | number>,
  activeFootprint: Polygon,
) {
  const zones = result.zones ?? [{ id: 'zone-1', name: 'Plangebiet', constraints: result.constraints, footprint: result.footprint }]

  const buildings = zones.map((zone) => buildCityGMLBuilding(zone, result, proposed, activeFootprint)).join('\n')

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<CityModel xmlns="http://www.opengis.net/citygml/2.0"
           xmlns:bldg="http://www.opengis.net/citygml/building/2.0"
           xmlns:gml="http://www.opengis.net/gml"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.opengis.net/citygml/2.0 http://schemas.opengis.net/citygml/2.0/cityGMLBase.xsd">
  <gml:name>${escapeXml(result.plan.name)}</gml:name>
  <gml:description>Generated by PLANRAUM — AI Bebauungsplan Reader. Municipality: ${escapeXml(result.plan.municipality)}</gml:description>
${buildings}
</CityModel>`

  const filename = `${result.plan.name || 'planraum'}_LOD2.gml`.replace(/\s+/g, '_')
  download(xml, filename, 'application/gml+xml')
}

function buildCityGMLBuilding(
  zone: PlanZone,
  result: ExtractionResult,
  proposed: Record<string, string | number>,
  activeFootprint: Polygon,
): string {
  const heightM = toNum(getConstraintValue(zone.constraints, 'max_height') ?? proposed['max_height'], 9)
  const roofLabel = String(getConstraintValue(zone.constraints, 'roof_type') ?? proposed['roof_type'] ?? 'unknown')
  const roofType = roofTypeFromLabel(roofLabel)
  const pitchDeg = toNum(getConstraintValue(zone.constraints, 'roof_pitch') ?? proposed['roof_pitch'], 35)
  const footprint = zone.footprint ?? activeFootprint
  const ring = footprint.coordinates[0]
  if (!ring || ring.length < 4) return ''

  // Eave height calculation (same as buildingGeometry.ts)
  const lons = ring.map((c) => c[0])
  const lats = ring.map((c) => c[1])
  const minLon = Math.min(...lons), maxLon = Math.max(...lons)
  const minLat = Math.min(...lats), maxLat = Math.max(...lats)
  const centerLat = (minLat + maxLat) / 2
  const mPerDegLon = 111320 * Math.cos((centerLat * Math.PI) / 180)
  const mPerDegLat = 110540
  const widthM = (maxLon - minLon) * mPerDegLon
  const heightDegM = (maxLat - minLat) * mPerDegLat
  const spanM = Math.min(widthM, heightDegM)
  const pitchRad = (pitchDeg * Math.PI) / 180
  const roofRise = Math.min((spanM / 2) * Math.tan(pitchRad), heightM * 0.6)
  const eaveH = roofType === 'flach' || roofType === 'unknown' ? heightM : Math.max(heightM - roofRise, heightM * 0.4)

  // Ground polygon (pos list: lon lat 0)
  const groundPos = ring.map((c) => `${c[0]} ${c[1]} 0`).join(' ')
  const eavePos = ring.map((c) => `${c[0]} ${c[1]} ${eaveH.toFixed(2)}`).join(' ')
  const roofPos = ring.map((c) => `${c[0]} ${c[1]} ${heightM.toFixed(2)}`).join(' ')

  // Wall surfaces (one per edge, from ground to eave)
  const wallSurfaces: string[] = []
  for (let i = 0; i < ring.length - 1; i++) {
    const [x1, y1] = ring[i]
    const [x2, y2] = ring[i + 1]
    const posList = `${x1} ${y1} 0 ${x2} ${y2} 0 ${x2} ${y2} ${eaveH.toFixed(2)} ${x1} ${y1} ${eaveH.toFixed(2)} ${x1} ${y1} 0`
    wallSurfaces.push(`        <bldg:boundedBy>
          <bldg:WallSurface>
            <bldg:lod2MultiSurface>
              <gml:MultiSurface>
                <gml:surfaceMember>
                  <gml:Polygon>
                    <gml:exterior>
                      <gml:LinearRing>
                        <gml:posList srsDimension="3">${posList}</gml:posList>
                      </gml:LinearRing>
                    </gml:exterior>
                  </gml:Polygon>
                </gml:surfaceMember>
              </gml:MultiSurface>
            </bldg:lod2MultiSurface>
          </bldg:WallSurface>
        </bldg:boundedBy>`)
  }

  // Roof surface
  const roofSurface = `        <bldg:boundedBy>
          <bldg:RoofSurface>
            <bldg:lod2MultiSurface>
              <gml:MultiSurface>
                <gml:surfaceMember>
                  <gml:Polygon>
                    <gml:exterior>
                      <gml:LinearRing>
                        <gml:posList srsDimension="3">${roofPos}</gml:posList>
                      </gml:LinearRing>
                    </gml:exterior>
                  </gml:Polygon>
                </gml:surfaceMember>
              </gml:MultiSurface>
            </bldg:lod2MultiSurface>
          </bldg:RoofSurface>
        </bldg:boundedBy>`

  // Ground surface
  const groundSurface = `        <bldg:boundedBy>
          <bldg:GroundSurface>
            <bldg:lod2MultiSurface>
              <gml:MultiSurface>
                <gml:surfaceMember>
                  <gml:Polygon>
                    <gml:exterior>
                      <gml:LinearRing>
                        <gml:posList srsDimension="3">${groundPos}</gml:posList>
                      </gml:LinearRing>
                    </gml:exterior>
                  </gml:Polygon>
                </gml:surfaceMember>
              </gml:MultiSurface>
            </bldg:lod2MultiSurface>
          </bldg:GroundSurface>
        </bldg:boundedBy>`

  return `  <cityObjectMember>
    <bldg:Building gml:id="${escapeXml(zone.id)}">
      <gml:name>${escapeXml(zone.name)}</gml:name>
      <bldg:measuredHeight uom="m">${heightM.toFixed(1)}</bldg:measuredHeight>
      <bldg:storeysAboveGround>${Math.round(toNum(getConstraintValue(zone.constraints, 'floors'), 2))}</bldg:storeysAboveGround>
      <bldg:roofType>${escapeXml(roofLabel)}</bldg:roofType>
${groundSurface}
${wallSurfaces.join('\n')}
${roofSurface}
    </bldg:Building>
  </cityObjectMember>`
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}
