import type { Polygon } from 'geojson'
import type { ExtractionResult, PlanZone, Constraint } from '../types'
import { buildProposedFeatures } from '../viewer/buildingGeometry'
import { roofTypeFromLabel } from './roof'

/** Trigger a browser download of a string as a file. */
function download(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function getConstraintValue(constraints: Constraint[], key: string): string | number | undefined {
  return constraints.find((c) => c.key === key)?.value
}

function toNum(v: string | number | undefined, fallback: number): number {
  if (v == null) return fallback
  const n = typeof v === 'number' ? v : Number(String(v).replace(',', '.'))
  return Number.isFinite(n) ? n : fallback
}

/**
 * Export the proposed building(s) as a 3D GeoJSON FeatureCollection.
 * Each zone produces wall + roof features with full metadata.
 * Directly importable into QGIS as a vector layer with 3D renderer.
 */
export function exportGeoJSON(
  result: ExtractionResult,
  proposed: Record<string, string | number>,
  activeFootprint: Polygon,
) {
  const zones = result.zones ?? [{ id: 'zone-1', name: 'Plangebiet', constraints: result.constraints, footprint: result.footprint }]

  const allFeatures: GeoJSON.Feature[] = []

  for (const zone of zones) {
    const heightM = toNum(getConstraintValue(zone.constraints, 'max_height') ?? proposed['max_height'], 9)
    const roofLabel = String(getConstraintValue(zone.constraints, 'roof_type') ?? proposed['roof_type'] ?? 'unknown')
    const roofType = roofTypeFromLabel(roofLabel)
    const pitchDeg = toNum(getConstraintValue(zone.constraints, 'roof_pitch') ?? proposed['roof_pitch'], 35)
    const footprint = zone.footprint ?? activeFootprint

    const fc = buildProposedFeatures(footprint, heightM, roofType, pitchDeg, true)

    for (const f of fc.features) {
      allFeatures.push({
        ...f,
        properties: {
          ...f.properties,
          zone_id: zone.id,
          zone_name: zone.name,
          plan_name: result.plan.name,
          plan_number: result.plan.planNumber ?? '',
          municipality: result.plan.municipality,
          crs: result.plan.crs,
          roof_type: roofLabel,
          roof_pitch: pitchDeg,
          max_height: heightM,
          grz: toNum(getConstraintValue(zone.constraints, 'grz'), 0),
          gfz: toNum(getConstraintValue(zone.constraints, 'gfz'), 0),
          floors: toNum(getConstraintValue(zone.constraints, 'floors'), 0),
        },
      })
    }
  }

  const geojson: GeoJSON.FeatureCollection = {
    type: 'FeatureCollection',
    features: allFeatures,
  }

  const filename = `${result.plan.name || 'planraum'}_3d.geojson`.replace(/\s+/g, '_')
  download(JSON.stringify(geojson, null, 2), filename, 'application/geo+json')
}

/**
 * Export as CityGML LOD2 — the format the hackathon challenge asks for.
 * Generates a minimal CityGML 2.0 document with Building elements containing
 * WallSurface and RoofSurface for each zone.
 */
export function exportCityGML(
  result: ExtractionResult,
  proposed: Record<string, string | number>,
  activeFootprint: Polygon,
) {
  const zones = result.zones ?? [{ id: 'zone-1', name: 'Plangebiet', constraints: result.constraints, footprint: result.footprint }]

  const buildings = zones.map((zone) => buildCityGMLBuilding(zone, result, proposed, activeFootprint)).join('\n')

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<CityModel xmlns="http://www.opengis.net/citygml/2.0"
           xmlns:bldg="http://www.opengis.net/citygml/building/2.0"
           xmlns:gml="http://www.opengis.net/gml"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.opengis.net/citygml/2.0 http://schemas.opengis.net/citygml/2.0/cityGMLBase.xsd">
  <gml:name>${escapeXml(result.plan.name)}</gml:name>
  <gml:description>Generated by PLANRAUM — AI Bebauungsplan Reader. Municipality: ${escapeXml(result.plan.municipality)}</gml:description>
${buildings}
</CityModel>`

  const filename = `${result.plan.name || 'planraum'}_LOD2.gml`.replace(/\s+/g, '_')
  download(xml, filename, 'application/gml+xml')
}

function buildCityGMLBuilding(
  zone: PlanZone,
  _result: ExtractionResult,
  proposed: Record<string, string | number>,
  activeFootprint: Polygon,
): string {
  const heightM = toNum(getConstraintValue(zone.constraints, 'max_height') ?? proposed['max_height'], 9)
  const roofLabel = String(getConstraintValue(zone.constraints, 'roof_type') ?? proposed['roof_type'] ?? 'unknown')
  const roofType = roofTypeFromLabel(roofLabel)
  const pitchDeg = toNum(getConstraintValue(zone.constraints, 'roof_pitch') ?? proposed['roof_pitch'], 35)
  const footprint = zone.footprint ?? activeFootprint
  const ring = footprint.coordinates[0]
  if (!ring || ring.length < 4) return ''

  // Eave height calculation (same as buildingGeometry.ts)
  const lons = ring.map((c) => c[0])
  const lats = ring.map((c) => c[1])
  const minLon = Math.min(...lons), maxLon = Math.max(...lons)
  const minLat = Math.min(...lats), maxLat = Math.max(...lats)
  const centerLat = (minLat + maxLat) / 2
  const mPerDegLon = 111320 * Math.cos((centerLat * Math.PI) / 180)
  const mPerDegLat = 110540
  const widthM = (maxLon - minLon) * mPerDegLon
  const heightDegM = (maxLat - minLat) * mPerDegLat
  const spanM = Math.min(widthM, heightDegM)
  const pitchRad = (pitchDeg * Math.PI) / 180
  const roofRise = Math.min((spanM / 2) * Math.tan(pitchRad), heightM * 0.6)
  const eaveH = roofType === 'flach' || roofType === 'unknown' ? heightM : Math.max(heightM - roofRise, heightM * 0.4)

  // Ground polygon (pos list: lon lat 0)
  const groundPos = ring.map((c) => `${c[0]} ${c[1]} 0`).join(' ')
  const roofPos = ring.map((c) => `${c[0]} ${c[1]} ${heightM.toFixed(2)}`).join(' ')

  // Wall surfaces (one per edge, from ground to eave)
  const wallSurfaces: string[] = []
  for (let i = 0; i < ring.length - 1; i++) {
    const [x1, y1] = ring[i]
    const [x2, y2] = ring[i + 1]
    const posList = `${x1} ${y1} 0 ${x2} ${y2} 0 ${x2} ${y2} ${eaveH.toFixed(2)} ${x1} ${y1} ${eaveH.toFixed(2)} ${x1} ${y1} 0`
    wallSurfaces.push(`        <bldg:boundedBy>
          <bldg:WallSurface>
            <bldg:lod2MultiSurface>
              <gml:MultiSurface srsName="EPSG:4326" srsDimension="3">
                <gml:surfaceMember>
                  <gml:Polygon srsName="EPSG:4326" srsDimension="3">
                    <gml:exterior>
                      <gml:LinearRing srsName="EPSG:4326" srsDimension="3">
                        <gml:posList srsDimension="3">${posList}</gml:posList>
                      </gml:LinearRing>
                    </gml:exterior>
                  </gml:Polygon>
                </gml:surfaceMember>
              </gml:MultiSurface>
            </bldg:lod2MultiSurface>
          </bldg:WallSurface>
        </bldg:boundedBy>`)
  }

  // Roof surface
  const roofSurface = `        <bldg:boundedBy>
          <bldg:RoofSurface>
            <bldg:lod2MultiSurface>
              <gml:MultiSurface srsName="EPSG:4326" srsDimension="3">
                <gml:surfaceMember>
                  <gml:Polygon srsName="EPSG:4326" srsDimension="3">
                    <gml:exterior>
                      <gml:LinearRing srsName="EPSG:4326" srsDimension="3">
                        <gml:posList srsDimension="3">${roofPos}</gml:posList>
                      </gml:LinearRing>
                    </gml:exterior>
                  </gml:Polygon>
                </gml:surfaceMember>
              </gml:MultiSurface>
            </bldg:lod2MultiSurface>
          </bldg:RoofSurface>
        </bldg:boundedBy>`

  // Ground surface
  const groundSurface = `        <bldg:boundedBy>
          <bldg:GroundSurface>
            <bldg:lod2MultiSurface>
              <gml:MultiSurface srsName="EPSG:4326" srsDimension="3">
                <gml:surfaceMember>
                  <gml:Polygon srsName="EPSG:4326" srsDimension="3">
                    <gml:exterior>
                      <gml:LinearRing srsName="EPSG:4326" srsDimension="3">
                        <gml:posList srsDimension="3">${groundPos}</gml:posList>
                      </gml:LinearRing>
                    </gml:exterior>
                  </gml:Polygon>
                </gml:surfaceMember>
              </gml:MultiSurface>
            </bldg:lod2MultiSurface>
          </bldg:GroundSurface>
        </bldg:boundedBy>`

  return `  <cityObjectMember>
    <bldg:Building gml:id="${escapeXml(zone.id)}">
      <gml:name>${escapeXml(zone.name)}</gml:name>
      <bldg:measuredHeight uom="m">${heightM.toFixed(1)}</bldg:measuredHeight>
      <bldg:storeysAboveGround>${Math.round(toNum(getConstraintValue(zone.constraints, 'floors'), 2))}</bldg:storeysAboveGround>
      <bldg:roofType>${escapeXml(roofLabel)}</bldg:roofType>
${groundSurface}
${wallSurfaces.join('\n')}
${roofSurface}
    </bldg:Building>
  </cityObjectMember>`
}

function escapeXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

/**
 * Export as CityJSON 2.0 — reliable QGIS import with full 3D geometry.
 * Generates a single Building CityObject with Ground, Wall, and Roof surfaces.
 */
export function exportCityJSON(
  result: ExtractionResult,
  proposed: Record<string, string | number>,
  activeFootprint: Polygon,
) {
  const zones = result.zones ?? [{ id: 'zone-1', name: 'Plangebiet', constraints: result.constraints, footprint: result.footprint }]

  const vertices: [number, number, number][] = []
  const vertexIndex = new Map<string, number>()
  const cityObjects: Record<string, CityJSONBuilding> = {}

  function addVertex(x: number, y: number, z: number): number {
    const key = `${x.toFixed(8)},${y.toFixed(8)},${z.toFixed(3)}`
    const existing = vertexIndex.get(key)
    if (existing != null) return existing
    const idx = vertices.length
    vertices.push([x, y, z])
    vertexIndex.set(key, idx)
    return idx
  }

  for (const zone of zones) {
    const heightM = toNum(getConstraintValue(zone.constraints, 'max_height') ?? proposed['max_height'], 9)
    const roofLabel = String(getConstraintValue(zone.constraints, 'roof_type') ?? proposed['roof_type'] ?? 'unknown')
    const roofType = roofTypeFromLabel(roofLabel)
    const pitchDeg = toNum(getConstraintValue(zone.constraints, 'roof_pitch') ?? proposed['roof_pitch'], 35)
    const footprint = zone.footprint ?? activeFootprint
    const ring = footprint.coordinates[0]
    if (!ring || ring.length < 4) continue

    // Compute eave height (same logic as CityGML and viewer)
    const lons = ring.map((c) => c[0])
    const lats = ring.map((c) => c[1])
    const minLon = Math.min(...lons), maxLon = Math.max(...lons)
    const minLat = Math.min(...lats), maxLat = Math.max(...lats)
    const centerLat = (minLat + maxLat) / 2
    const mPerDegLon = 111320 * Math.cos((centerLat * Math.PI) / 180)
    const mPerDegLat = 110540
    const widthM = (maxLon - minLon) * mPerDegLon
    const heightDegM = (maxLat - minLat) * mPerDegLat
    const spanM = Math.min(widthM, heightDegM)
    const pitchRad = (pitchDeg * Math.PI) / 180
    const roofRise = Math.min((spanM / 2) * Math.tan(pitchRad), heightM * 0.6)
    const eaveH = roofType === 'flach' || roofType === 'unknown' ? heightM : Math.max(heightM - roofRise, heightM * 0.4)

    // Boundary indices for ground ring (closed, exclude last duplicate)
    const n = ring.length - 1

    // Ground surface: ring at z=0
    const groundBoundary = ring.slice(0, n).map(([x, y]) => addVertex(x, y, 0))

    // Roof surface: ring at z=heightM
    const roofBoundary = ring.slice(0, n).map(([x, y]) => addVertex(x, y, heightM))

    // Wall surfaces: one quad per edge, ground to eave
    const wallBoundaries: number[][] = []
    for (let i = 0; i < n; i++) {
      const j = (i + 1) % n
      wallBoundaries.push([
        addVertex(ring[i][0], ring[i][1], 0),
        addVertex(ring[j][0], ring[j][1], 0),
        addVertex(ring[j][0], ring[j][1], eaveH),
        addVertex(ring[i][0], ring[i][1], eaveH),
      ])
    }

    const surfaces: number[][][] = []
    const semantics: { type: string }[] = []
    const semanticValues: number[] = []

    // Ground
    surfaces.push([groundBoundary])
    semantics.push({ type: 'GroundSurface' })
    semanticValues.push(0)

    // Roof
    surfaces.push([roofBoundary])
    semantics.push({ type: 'RoofSurface' })
    semanticValues.push(1)

    // Walls
    const wallSemanticIdx = semantics.length
    semantics.push({ type: 'WallSurface' })
    for (const wb of wallBoundaries) {
      surfaces.push([wb])
      semanticValues.push(wallSemanticIdx)
    }

    cityObjects[zone.id] = {
      type: 'Building',
      attributes: {
        measuredHeight: heightM,
        roofType: roofLabel,
        storeysAboveGround: Math.round(toNum(getConstraintValue(zone.constraints, 'floors'), 2)),
        planName: result.plan.name,
        municipality: result.plan.municipality,
      },
      geographicalExtent: [minLon, minLat, 0, maxLon, maxLat, heightM],
      geometry: [{
        type: 'Solid',
        lod: '2',
        boundaries: [surfaces],
        semantics: {
          surfaces: semantics,
          values: [semanticValues],
        },
      }],
    }
  }

  const cityjson = {
    type: 'CityJSON',
    version: '2.0',
    metadata: {
      referenceSystem: 'https://www.opengis.net/def/crs/EPSG/0/4326',
      title: result.plan.name,
      identifier: result.plan.planNumber ?? '',
    },
    CityObjects: cityObjects,
    vertices,
  }

  const filename = `${result.plan.name || 'planraum'}_3d.city.json`.replace(/\s+/g, '_')
  download(JSON.stringify(cityjson, null, 2), filename, 'application/city+json')
}

interface CityJSONBuilding {
  type: string
  attributes: Record<string, unknown>
  geographicalExtent: number[]
  geometry: {
    type: string
    lod: string
    boundaries: number[][][][]
    semantics: {
      surfaces: { type: string }[]
      values: number[][]
    }
  }[]
}
